A couple of make dist/make distcheck fixes:
  - Pass --with-boost, --with-parmetis, and --with-zoltan options to
    DISTCHECK_CONFIGURE_FLAGS if they were given to main configure
    so that the configure in make distcheck will succeed.
  - Cause make dist to bomb out if using libtool 1.5.x

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -5,3 +5,13 @@
 ACLOCAL_AMFLAGS = -I config
 
 SUBDIRS = components sst
+
+dist-hook:
+	@ if test $(SST_DISTABLE_LIBTOOL) -eq 0 ; then \
+	  echo "*** WARNING: Your version of Libtool is too old for 'make dist'" ; \
+	  echo "*** Libtool version 2.2.0 or higher is required." ; \
+	  echo "*** Your libtool reports:" ; \
+	  ./libtool --version ; \
+	  echo "*** Can not continue!" ; \
+	  exit 1 ; \
+	fi
